adding calculator.js with some calculator functions
rburlevich/rburlevich.github.io pull request #1
Opened 2017-03-20 20:40 UTC by rburlevich

2017-03-22 05:20 UTC, NikitaSedyx requested changes

2017-03-22 05:20 UTC, NikitaSedyx commented on index.html
> +		Hello!
1. new folder for task
2. wrong indentations, 2 spaces is correct
3. empty line at the EOF in each file, you see red sign

2017-03-27 18:40 UTC, NikitaSedyx approved these changes
please fix code style

2017-03-27 18:40 UTC, NikitaSedyx commented on calculator/js/calculator.js
> +return a + b;
nit: could you make indentations?

2017-03-27 18:51 UTC, rburlevich commented on calculator/js/calculator.js
> +return a + b;
done, please review again

2017-03-27 18:57 UTC, NikitaSedyx commented on calculator/js/calculator.js
> +return a + b;
you have my approve, it was a nit

2020-04-23 13:48 UTC, closed without merging